[[news]]
date = "2025-08"
content = "Our paper *Accurate-geometry-embodied finite element method for phonon Boltzmann transport equation* was published in **Computer Physics Communications**. 🎉"

[[news]]
date = "2025-03"
content = "Presented at the HKUST SIAM Student Chapter Annual Meeting 2025."

[[news]]
date = "2024"
content = "Gave a talk at the minisymposium of EASIAM 2024."
