type = "publication"
title = "Research"
description = "My publications and research projects. You can also find my articles on my [Google Scholar profile](https://scholar.google.com/citations?user=rocwHG0AAAAJ&hl=en)."
source = "publications.bib"
